# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    app_store_connect_api_key(
    key_id: "XXXXXX",
    issuer_id: "xxxx-xxxxx-xxxx-xxxxxx",
    key_filepath: "./AuthKey.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
end

platform :ios do
  desc "Update certificates"
  lane :updateCertificates do
    match_nuke(type: "development")
    match_nuke(type: "appstore")
  end

  desc "Get certificates"
  lane :certificates do
    match(type: "development", app_identifier: ["com.rnfastlane"])
    match(type: "appstore", app_identifier: ["com.rnfastlane"])
  end

  desc "Build a new release ipa for testing."
  lane :testIpa do|options|
    puts "Build a new release ipa for testing."
    versionNumber = prompt(text: "VersionNumber(eg. 1.0.1): ")
    buildNumber = prompt(text: "BuildNumber(eg. 1): ")
    rocket
    match(
      type: "appstore",
      git_url: "https://you-private-repo-to-store-certs-and-profile.git",
      app_identifier: "com.rnfastlane"
    )
    increment_version_number(version_number: versionNumber)
    increment_build_number(build_number: buildNumber)
    gym(
      scheme: "RNFastlane",
      output_name: "fastlaneApp.ipa",
      clean: true,
      include_bitcode: true
    )
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit a new Build to Apple TestFlight"
  lane :releaseTestflight do|options|
    puts "Submit a new Build to Apple TestFlight"
    versionNumber = prompt(text: "VersionNumber(eg. 1.0.1): ")
    buildNumber = prompt(text: "BuildNumber(eg. 1): ")
    rocket
    match(
      type: "appstore",
      git_url: "https://you-private-repo-to-store-certs-and-profile.git",
      app_identifier: "com.rnfastlane"
    )
    increment_version_number(version_number: versionNumber)
    increment_build_number(build_number: buildNumber)
    gym(
      scheme: "RNFastlane",
      output_name: "fastlaneApp.ipa",
      clean: true
    )
    pilot
    # add actions here: https://docs.fastlane.tools/actions
  end
end
